import json
import asyncio
import os
import google.generativeai as genai
from sqlalchemy.orm import Session
from app.models.models import Analysis, Resume
from app.services.prompts import (
    ATS_PROMPT, SOFT_SKILLS_PROMPT, PROJECTS_PROMPT,
    CERTS_PROMPT, JOB_MATCH_PROMPT, SYNTHESIZER_PROMPT
)

# Free-Tier setup for Hackathon: Add GEMINI_API_KEY to your .env file
GENAI_API_KEY = os.environ.get("GEMINI_API_KEY")
if GENAI_API_KEY:
    genai.configure(api_key=GENAI_API_KEY)

async def run_agent(agent_name: str, system_prompt: str, input_text: str) -> str:
    """Execute a single agent prompt via Gemini asynchronously."""
    if not GENAI_API_KEY:
        # Fallback Mock if key is not configured, ensuring UI doesn't crash during hackathon dev
        return ""

    try:
        # Utilizing gemini-1.5-flash as it is lightning fast and free-tier friendly
        model = genai.GenerativeModel('gemini-1.5-flash') 
        prompt = f"{system_prompt}\n\nINPUT DATA:\n{input_text}"
        
        # Using to_thread to safely bridge synchronous SDK calls inside asyncio runner
        response = await asyncio.to_thread(model.generate_content, prompt)
        return response.text
    except Exception as e:
        print(f"Error in agent {agent_name}: {e}")
        return ""

async def execute_multi_agent_pipeline(resume_text: str, role: str, company: str) -> dict:
    """Orchestrates Phase 2 Workflow: Parallel processing -> Synthesis"""
    input_data = f"Resume:\n{resume_text}\n\nTarget Role: {role}\nTarget Company: {company}"
    
    # 1. Run Analysis Agents in Parallel
    results = await asyncio.gather(
        run_agent("ats_checker", ATS_PROMPT, input_data),
        run_agent("soft_skills", SOFT_SKILLS_PROMPT, input_data),
        run_agent("projects", PROJECTS_PROMPT, input_data),
        run_agent("certs", CERTS_PROMPT, input_data),
        run_agent("job_match", JOB_MATCH_PROMPT, input_data)
    )
    
    ats_res, soft_res, proj_res, cert_res, job_res = results
    
    # 2. Synthesize Results (Conflict Resolution & Final Formatting)
    synth_input = f"ATS REPORT:\n{ats_res}\n\nSOFT SKILLS:\n{soft_res}\n\nPROJECTS:\n{proj_res}\n\nCERTIFICATIONS:\n{cert_res}\n\nJOB MATCHES:\n{job_res}"
    final_output_text = await run_agent("synthesizer", SYNTHESIZER_PROMPT, synth_input)
    
    # Clean JSON markers generated by LLM if any
    final_output_text = final_output_text.replace("```json", "").replace("```", "").strip()
        
    try:
        return json.loads(final_output_text) if final_output_text else {}
    except Exception as e:
        print(f"Failed to parse JSON Synthesizer output: {e}\n{final_output_text}")
        return {}

def run_pipeline_sync(resume_text: str, role: str, company: str):
    """Bridge for FastAPI synchronous background tasks"""
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    result = loop.run_until_complete(execute_multi_agent_pipeline(resume_text, role, company))
    loop.close()
    return result

def trigger_multi_agent_pipeline(analysis_id: int, db: Session):
    """Main Entry point accessed by the API."""
    try:
        analysis = db.query(Analysis).filter(Analysis.id == analysis_id).first()
        if not analysis:
            return
            
        resume = db.query(Resume).filter(Resume.id == analysis.resume_id).first()
        resume_text = resume.parsed_text if resume else ""
        role = analysis.job_role or "General Role"
        company = analysis.company_name or "General Company"
        
        # Execute the AI Pipeline
        final_data = run_pipeline_sync(resume_text, role, company)
        
        # If API key isn't set or pipeline failed, map a mock response. Else, map real response.
        if not final_data:
            analysis.ats_score = 65
            analysis.missing_skills = json.dumps(["Cross-functional Communication", "Client Negotiation"])
            analysis.project_suggestions = json.dumps(["Deploy a cloud architecture and write a postmortem", "Create a collaborative open-source widget"])
            analysis.certification_suggestions = json.dumps(["AWS Cloud Practitioner", "Agile Fundamentals SDK"])
            analysis.role_suggestions = json.dumps([role, "Junior Dev", "Technical Writer"])
            analysis.explanation = "MOCK RUN: Please define GEMINI_API_KEY in your `.env` file to see the real AI Multi-Agent pipeline in action!"
        else:
            analysis.ats_score = final_data.get("ats_score", 50)
            analysis.missing_skills = json.dumps(final_data.get("soft_skills_missing", []))
            analysis.project_suggestions = json.dumps(final_data.get("project_recommendations", []))
            analysis.certification_suggestions = json.dumps(final_data.get("certification_recommendations", []))
            analysis.role_suggestions = json.dumps(final_data.get("suitable_jobs", []))
            analysis.explanation = final_data.get("detailed_explanation", "")
            
        analysis.status = "completed"
        db.commit()
    except Exception as e:
        print(f"CRITICAL Pipeline error: {e}")
        analysis.status = "failed"
        db.commit()
